[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "0.9.2"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"
  
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "0.22.0"
  
[prune]
  go-tests = true
  unused-packages = true
